# Generated by Django 5.2 on 2025-04-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('YEL', 'Żółty'), ('RED', 'Czerwony'), ('BLU', 'Niebieski'), ('GRN', 'Green'), ('PIN', 'Pink')], max_length=3)),
                ('size', models.CharField(choices=[('S', 'Maly'), ('M', 'Średni'), ('L', 'Duzy')], max_length=1)),
                ('typ', models.CharField(choices=[('N', 'Narty'), ('S', 'Snowboard')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezerwacje', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'rezerwacje',
            },
        ),
    ]
