# Generated by Django 5.2 on 2025-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='typ',
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('S', 'SUV'), ('SP', 'SPORT'), ('H', 'HATCHBACK')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
