# Generated by Django 5.2 on 2025-04-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_typ_car_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='description',
            new_name='specification',
        ),
    ]
