# Generated by Django 5.2 on 2025-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7),
        ),
    ]
